version: '3.8'

services:
  # Local DynamoDB for development
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - expense-tracker-network

  # Expense Tracker API
  expense-tracker-api:
    build: .
    container_name: expense-tracker-api
    ports:
      - "8080:8080"
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - dynamodb-local
    networks:
      - expense-tracker-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/v1/expenses/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  expense-tracker-network:
    driver: bridge

volumes:
  dynamodb-data:
