# Local Development Configuration
spring:
  application:
    name: expense-tracker-local
  
  # Disable AWS for local testing
  autoconfigure:
    exclude:
      - com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder

# Server Configuration
server:
  port: 8080

# Logging
logging:
  level:
    com.expensetracker: INFO
    root: INFO
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Disable AWS for local development
aws:
  region: us-east-1
